# Site
name: 'David Dragan Blog'
description: 'This is my blog. I post here occasionally to keep my writing skills sharp.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
#baseurl: '/mundana-theme-jekyll'
disqus: 'dd9blog'
email: 'daviddragan377@gmail.com'
#mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    david:
      name:           David
      site:           https://daviddragan1.github.io/ddd
      avatar:         /assets/images/avatar1.jpg
      bio:            "I'm David, freelance web developer and lifelong student."
      email:          daviddragan377@gmail.com
      twitter:        https://twitter.com/daviddragan377
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: david
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
